name: Lint, Test, and Deploy

on: [push, pull_request]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint  # Make sure you have a lint script in package.json

  build:
    name: Build and Package
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Package Application
        run: zip -r my-app.zip . -x "*.git*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-app
          path: my-app.zip

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged-app

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOYACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETDEPLOY_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Upload to S3
        run: aws s3 cp my-app.zip s3://tayoacebucket/

      - name: Deploy to EC2 via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name TTcode \
            --deployment-group-name Tayoaceproduction \
            --s3-location bucket=tayoacebucket,key=my-app.zip,bundleType=zip

